-- System: accounts, roles, function catalog and permission matrices. Run 00-helpers.sql first.
-- Safe to rerun on a new or an existing database. Back up an existing database first.

CREATE TABLE IF NOT EXISTS sys_users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(100) NOT NULL,
    ma_dvcs varchar(20) NOT NULL DEFAULT '',
    email varchar(150),
    phone varchar(20),
    department varchar(100) NOT NULL DEFAULT '',
    avatar text NOT NULL DEFAULT '',
    theme_pref varchar(10) NOT NULL DEFAULT 'light',
    notifications_enabled boolean NOT NULL DEFAULT true,
    security_version integer NOT NULL DEFAULT 1,
    is_active boolean NOT NULL DEFAULT true,
    employee_code text NOT NULL DEFAULT '',
    auth_fl varchar(25) NOT NULL DEFAULT '',
    enablefl integer NOT NULL DEFAULT 1,
    validflg integer NOT NULL DEFAULT 1,
    gender boolean NOT NULL DEFAULT false,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1'
);
ALTER TABLE sys_users ADD COLUMN IF NOT EXISTS department varchar(100) NOT NULL DEFAULT '';
ALTER TABLE sys_users ADD COLUMN IF NOT EXISTS avatar text NOT NULL DEFAULT '';
ALTER TABLE sys_users ADD COLUMN IF NOT EXISTS theme_pref varchar(10) NOT NULL DEFAULT 'light';
ALTER TABLE sys_users ADD COLUMN IF NOT EXISTS notifications_enabled boolean NOT NULL DEFAULT true;
ALTER TABLE sys_users ADD COLUMN IF NOT EXISTS security_version integer NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_users_name ON sys_users (lower(user_name)) WHERE validflg = 1;

CREATE TABLE IF NOT EXISTS sys_role (
    role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(50) NOT NULL,
    role_name varchar(100) NOT NULL,
    description text,
    validflg smallint NOT NULL DEFAULT 1,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1'
);
-- Older databases identified the admin role by role_name = 'ADMIN'; the code is copied from the name.
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS role_code varchar(50);
UPDATE sys_role SET role_code = upper(left(regexp_replace(role_name, '\s+', '_', 'g'), 50)) WHERE role_code IS NULL;
ALTER TABLE sys_role ALTER COLUMN role_code SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_role_name ON sys_role (role_name);
CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_role_code ON sys_role (role_code);

-- Function catalog: menuid0 = frontend SubMenuKey. The API inserts missing codes at startup.
CREATE TABLE IF NOT EXISTS sys_command (
    menuid0 varchar(64) PRIMARY KEY,
    menuid varchar(64) NOT NULL DEFAULT '',
    text varchar(100) NOT NULL DEFAULT '',
    text2 varchar(100) NOT NULL DEFAULT '',
    ma_ct varchar(3) NOT NULL DEFAULT '',
    report varchar(100) NOT NULL DEFAULT '',
    command varchar(100) NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    title2 text NOT NULL DEFAULT '',
    basicright smallint NOT NULL DEFAULT 0,
    picture1 text NOT NULL DEFAULT '',
    picture2 text NOT NULL DEFAULT '',
    type varchar(3) NOT NULL DEFAULT '',
    sysid varchar(50) NOT NULL DEFAULT '',
    syscode varchar(50) NOT NULL DEFAULT '',
    hide_yn smallint NOT NULL DEFAULT 0,
    hide_yn2 smallint,
    ds_dvcs text NOT NULL DEFAULT ''
);
ALTER TABLE sys_command ALTER COLUMN menuid0 TYPE varchar(64);
ALTER TABLE sys_command ALTER COLUMN menuid TYPE varchar(64);

CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_role_command (
    role_id integer NOT NULL,
    menuid0 varchar(64) NOT NULL,
    can_view boolean NOT NULL DEFAULT false,
    can_add boolean NOT NULL DEFAULT false,
    can_edit boolean NOT NULL DEFAULT false,
    can_delete boolean NOT NULL DEFAULT false,
    can_print boolean NOT NULL DEFAULT false,
    can_import boolean NOT NULL DEFAULT false,
    can_export boolean NOT NULL DEFAULT false,
    can_search boolean NOT NULL DEFAULT false,
    can_reload boolean NOT NULL DEFAULT false,
    can_copy boolean NOT NULL DEFAULT false,
    can_approve boolean NOT NULL DEFAULT false,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (role_id, menuid0)
);
ALTER TABLE sys_role_command ALTER COLUMN menuid0 TYPE varchar(64);

CREATE TABLE IF NOT EXISTS sys_user_command (
    user_id integer NOT NULL,
    menuid0 varchar(64) NOT NULL,
    can_view boolean NOT NULL DEFAULT false,
    can_add boolean NOT NULL DEFAULT false,
    can_edit boolean NOT NULL DEFAULT false,
    can_delete boolean NOT NULL DEFAULT false,
    can_print boolean NOT NULL DEFAULT false,
    can_import boolean NOT NULL DEFAULT false,
    can_export boolean NOT NULL DEFAULT false,
    can_search boolean NOT NULL DEFAULT false,
    can_reload boolean NOT NULL DEFAULT false,
    can_copy boolean NOT NULL DEFAULT false,
    can_approve boolean NOT NULL DEFAULT false,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (user_id, menuid0)
);
ALTER TABLE sys_user_command ALTER COLUMN menuid0 TYPE varchar(64);

-- Audit user ids used to be varchar(5).
ALTER TABLE sys_users ALTER COLUMN createid TYPE varchar(20), ALTER COLUMN updateid TYPE varchar(20);
ALTER TABLE sys_role ALTER COLUMN createid TYPE varchar(20), ALTER COLUMN updateid TYPE varchar(20);
ALTER TABLE sys_user_role ALTER COLUMN createid TYPE varchar(20), ALTER COLUMN updateid TYPE varchar(20);
ALTER TABLE sys_role_command ALTER COLUMN createid TYPE varchar(20), ALTER COLUMN updateid TYPE varchar(20);
ALTER TABLE sys_user_command ALTER COLUMN createid TYPE varchar(20), ALTER COLUMN updateid TYPE varchar(20);

-- No foreign keys: tables are linked by their id/code columns and the API checks the links.
SELECT sys_drop_foreign_keys('sys_user_role', 'sys_role_command', 'sys_user_command');
-- Indexes on the link columns.
CREATE INDEX IF NOT EXISTS ix_sys_user_role_role ON sys_user_role (role_id);
CREATE INDEX IF NOT EXISTS ix_sys_role_command_menu ON sys_role_command (menuid0);
CREATE INDEX IF NOT EXISTS ix_sys_user_command_menu ON sys_user_command (menuid0);

-- Special rights on top of the five actions (SpecialRightCatalog), e.g. inv_receipt + VIEW_PRICE.
-- A row means granted. The user's own set applies when the user has an own matrix (sys_user_command).
CREATE TABLE IF NOT EXISTS sys_role_right (
    role_id integer NOT NULL,
    menuid0 varchar(64) NOT NULL,
    right_code varchar(50) NOT NULL,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (role_id, menuid0, right_code)
);

CREATE TABLE IF NOT EXISTS sys_user_right (
    user_id integer NOT NULL,
    menuid0 varchar(64) NOT NULL,
    right_code varchar(50) NOT NULL,
    createtime timestamp,
    createid varchar(20),
    updatetime timestamp,
    updateid varchar(20),
    status varchar(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (user_id, menuid0, right_code)
);
