-- System: notifications and per-user read / dismissed state. Safe to rerun.
-- Older versions named these tables erp_notification / erp_notification_read; they are renamed.

SELECT sys_rename_table('erp_notification', 'sys_notification');
SELECT sys_rename_column('sys_notification', 'Id', 'id');
SELECT sys_rename_column('sys_notification', 'Title', 'title');
SELECT sys_rename_column('sys_notification', 'Body', 'body');
SELECT sys_rename_column('sys_notification', 'Type', 'type');
SELECT sys_rename_column('sys_notification', 'LinkModule', 'link_module');
SELECT sys_rename_column('sys_notification', 'UnitCode', 'unit_code');
SELECT sys_rename_column('sys_notification', 'PlantCode', 'plant_code');
SELECT sys_rename_column('sys_notification', 'RecipientUserId', 'recipient_user_id');
SELECT sys_rename_column('sys_notification', 'CreatedAtUtc', 'created_at_utc');
SELECT sys_rename_column('sys_notification', 'ExpiresAtUtc', 'expires_at_utc');
SELECT sys_rename_column('sys_notification', 'CreatedByUserId', 'created_by_user_id');
SELECT sys_rename_constraint('sys_notification', 'erp_notification_pkey', 'sys_notification_pkey');
SELECT sys_rename_constraint('sys_notification', 'ix_erp_notification_inbox', 'ix_sys_notification_inbox');
SELECT sys_rename_constraint('sys_notification', 'ix_erp_notification_target', 'ix_sys_notification_target');

CREATE TABLE IF NOT EXISTS sys_notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    body text NOT NULL,
    type varchar(20) NOT NULL DEFAULT 'info',
    link_module varchar(64),
    unit_code varchar(20),
    recipient_user_id integer,
    created_at_utc timestamp with time zone NOT NULL,
    expires_at_utc timestamp with time zone,
    created_by_user_id integer NOT NULL
);
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS type varchar(20) NOT NULL DEFAULT 'info';
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS link_module varchar(64);
-- Link to one document (function code + document id), e.g. inv_receipt / PNK-0001.
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS link_function varchar(64);
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS link_document_id varchar(64);
CREATE INDEX IF NOT EXISTS ix_sys_notification_created ON sys_notification (created_at_utc);
CREATE INDEX IF NOT EXISTS ix_sys_notification_inbox ON sys_notification (unit_code, recipient_user_id, created_at_utc);

SELECT sys_rename_table('erp_notification_read', 'sys_notification_read');
SELECT sys_rename_column('sys_notification_read', 'NotificationId', 'notification_id');
SELECT sys_rename_column('sys_notification_read', 'UserId', 'user_id');
SELECT sys_rename_column('sys_notification_read', 'ReadAtUtc', 'read_at_utc');
SELECT sys_rename_column('sys_notification_read', 'DismissedAtUtc', 'dismissed_at_utc');
SELECT sys_rename_constraint('sys_notification_read', 'erp_notification_read_pkey', 'sys_notification_read_pkey');
SELECT sys_rename_constraint('sys_notification_read', 'ix_erp_notification_read_user', 'ix_sys_notification_read_user');

CREATE TABLE IF NOT EXISTS sys_notification_read (
    notification_id bigint NOT NULL,
    user_id integer NOT NULL,
    read_at_utc timestamp with time zone NOT NULL,
    dismissed_at_utc timestamp with time zone,
    PRIMARY KEY (notification_id, user_id)
);
ALTER TABLE sys_notification_read ADD COLUMN IF NOT EXISTS dismissed_at_utc timestamp with time zone;
SELECT sys_drop_foreign_keys('sys_notification_read');
CREATE INDEX IF NOT EXISTS ix_sys_notification_read_user ON sys_notification_read (user_id);
