-- System: JSON sections of the frontend settings screens. Safe to rerun.
-- scope is 'GLOBAL' or 'U:<unit code>'; a unit value overrides the global one.
-- Older versions named this table erp_setting with "PascalCase" columns; it is renamed.

SELECT sys_rename_table('erp_setting', 'sys_setting');
SELECT sys_rename_column('sys_setting', 'Id', 'id');
SELECT sys_rename_column('sys_setting', 'Key', 'key');
SELECT sys_rename_column('sys_setting', 'Value', 'value');
SELECT sys_rename_column('sys_setting', 'Scope', 'scope');
SELECT sys_rename_column('sys_setting', 'IsPublic', 'is_public');
SELECT sys_rename_column('sys_setting', 'UpdatedAtUtc', 'updated_at_utc');
SELECT sys_rename_column('sys_setting', 'UpdatedByUserId', 'updated_by_user_id');
SELECT sys_rename_constraint('sys_setting', 'erp_setting_pkey', 'sys_setting_pkey');
SELECT sys_rename_constraint('sys_setting', 'ux_erp_setting_key_scope', 'ux_sys_setting_key_scope');

CREATE TABLE IF NOT EXISTS sys_setting (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key varchar(100) NOT NULL,
    value text NOT NULL,
    scope varchar(50) NOT NULL,
    is_public boolean NOT NULL DEFAULT true,
    updated_at_utc timestamp with time zone NOT NULL,
    updated_by_user_id integer NOT NULL,
    CONSTRAINT ux_sys_setting_key_scope UNIQUE (key, scope)
);
