-- System: approval workflow of documents. Safe to rerun. Run 00-helpers.sql first.

-- "Documents of {menuid0} created by {requester} in {unit_code}, from {min_amount}, are approved at
-- {level} by {approver}". Rules of the same level are combined; levels run in order.
CREATE TABLE IF NOT EXISTS sys_approval_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menuid0 varchar(64) NOT NULL,
    unit_code varchar(20),
    level integer NOT NULL DEFAULT 1,
    requester_type varchar(20) NOT NULL DEFAULT 'ANY',   -- ANY | USER | ROLE | DEPARTMENT
    requester_value varchar(100),
    min_amount numeric(18,2),
    approver_type varchar(20) NOT NULL,                  -- USER | ROLE
    approver_value varchar(100) NOT NULL,
    note varchar(500),
    is_active boolean NOT NULL DEFAULT true,
    updated_at_utc timestamp with time zone NOT NULL,
    updated_by_user_id integer NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sys_approval_rule_menu ON sys_approval_rule (menuid0, level);

-- One row per approval level of one submission (round) of a document.
CREATE TABLE IF NOT EXISTS sys_document_approval (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menuid0 varchar(64) NOT NULL,
    document_id varchar(64) NOT NULL,
    document_title varchar(200),
    unit_code varchar(20) NOT NULL,
    amount numeric(18,2),
    round integer NOT NULL DEFAULT 1,
    level integer NOT NULL,
    approver_user_ids text NOT NULL,                     -- comma-separated user ids allowed on this level
    approver_label varchar(300),
    status varchar(20) NOT NULL,                         -- WAITING | PENDING | APPROVED | REJECTED | CANCELLED
    requested_by_user_id integer NOT NULL,
    requested_at_utc timestamp with time zone NOT NULL,
    acted_by_user_id integer,
    acted_at_utc timestamp with time zone,
    note varchar(1000)
);
CREATE INDEX IF NOT EXISTS ix_sys_document_approval_doc ON sys_document_approval (menuid0, document_id, round);
CREATE INDEX IF NOT EXISTS ix_sys_document_approval_pending ON sys_document_approval (unit_code, status);