-- System: currencies and exchange rates. Safe to rerun. Run after 04-system-config.sql.
-- Older versions kept both lists as JSON settings (FRONTEND_CURRENCIES / FRONTEND_EXCHANGE_RATES);
-- they are copied into the tables, then removed.

CREATE TABLE IF NOT EXISTS sys_currency (
    code varchar(10) PRIMARY KEY,
    name varchar(100) NOT NULL,
    symbol varchar(10) NOT NULL DEFAULT '',
    decimal_places smallint NOT NULL DEFAULT 2,
    is_base boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0
);
-- At most one base (accounting) currency.
CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_currency_base ON sys_currency (is_base) WHERE is_base;

CREATE TABLE IF NOT EXISTS sys_exchange_rate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code varchar(10) NOT NULL,
    rate_date date NOT NULL,
    buy_rate numeric(18,6) NOT NULL DEFAULT 0,
    sell_rate numeric(18,6) NOT NULL DEFAULT 0,
    accounting_rate numeric(18,6) NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    updated_by_user_id integer NOT NULL,
    CONSTRAINT ux_sys_exchange_rate_day UNIQUE (currency_code, rate_date)
);

INSERT INTO sys_currency (code, name, symbol, decimal_places, is_base, is_active, sort_order)
SELECT upper(c->>'code'), coalesce(c->>'nameVi', c->>'code'), coalesce(c->>'symbol', ''),
       coalesce((c->>'decimalPlaces')::smallint, 2),
       -- Only the first currency flagged as base stays the base.
       coalesce((c->>'isBaseCurrency')::boolean, false)
           AND NOT EXISTS (SELECT 1 FROM sys_currency WHERE is_base)
           AND t.n = (SELECT min(t2.n) FROM jsonb_array_elements(s.value::jsonb) WITH ORDINALITY AS t2(c2, n)
                      WHERE coalesce((t2.c2->>'isBaseCurrency')::boolean, false)),
       coalesce(c->>'status', 'active') = 'active', t.n
FROM sys_setting s, jsonb_array_elements(s.value::jsonb) WITH ORDINALITY AS t(c, n)
WHERE s.key = 'FRONTEND_CURRENCIES' AND s.scope = 'GLOBAL' AND coalesce(c->>'code', '') <> ''
ON CONFLICT (code) DO NOTHING;

INSERT INTO sys_exchange_rate (currency_code, rate_date, buy_rate, sell_rate, accounting_rate, updated_at_utc, updated_by_user_id)
SELECT upper(r->>'currencyCode'), (r->>'date')::date, coalesce((r->>'buyRate')::numeric, 0), coalesce((r->>'sellRate')::numeric, 0),
       coalesce((r->>'accountingRate')::numeric, (r->>'buyRate')::numeric), now(), 0
FROM sys_setting s, jsonb_array_elements(s.value::jsonb) AS r
WHERE s.key = 'FRONTEND_EXCHANGE_RATES' AND s.scope = 'GLOBAL'
  AND EXISTS (SELECT 1 FROM sys_currency c WHERE c.code = upper(r->>'currencyCode') AND NOT c.is_base)
  AND coalesce((r->>'accountingRate')::numeric, (r->>'buyRate')::numeric, 0) > 0
ON CONFLICT (currency_code, rate_date) DO NOTHING;

DELETE FROM sys_setting WHERE key IN ('FRONTEND_CURRENCIES', 'FRONTEND_EXCHANGE_RATES');
