-- Goods receipts and stock movements. Safe to rerun. No foreign keys by project convention.
CREATE TABLE IF NOT EXISTS erp_goods_receipt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL UNIQUE,
    unit_code varchar(20) NOT NULL,
    document_date date NOT NULL,
    created_date date NOT NULL,
    warehouse_code varchar(20) NOT NULL,
    voucher_type varchar(100) NOT NULL,
    currency_code varchar(10) NOT NULL DEFAULT 'VND',
    exchange_rate numeric(18,6) NOT NULL DEFAULT 1,
    supplier_name varchar(200),
    deliverer_name varchar(200),
    note varchar(1000),
    status varchar(20) NOT NULL DEFAULT 'Draft',
    total_value numeric(18,2) NOT NULL DEFAULT 0,
    approved_by_user_id integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by integer,
    updated_at timestamptz,
    updated_by integer,
    CONSTRAINT ck_erp_goods_receipt_status CHECK (status IN ('Draft','Pending','Approved','Posted','Cancelled')),
    CONSTRAINT ck_erp_goods_receipt_rate CHECK (exchange_rate > 0)
);
CREATE INDEX IF NOT EXISTS ix_erp_goods_receipt_unit_date ON erp_goods_receipt(unit_code, document_date DESC);
CREATE INDEX IF NOT EXISTS ix_erp_goods_receipt_warehouse ON erp_goods_receipt(warehouse_code);

CREATE TABLE IF NOT EXISTS erp_goods_receipt_line (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id bigint NOT NULL,
    kind varchar(20) NOT NULL,
    line_no integer NOT NULL,
    product_code varchar(64) NOT NULL,
    product_name varchar(200) NOT NULL,
    unit varchar(30) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_price numeric(18,4) NOT NULL,
    amount numeric(18,2) NOT NULL,
    lot_number varchar(64),
    position varchar(100),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by integer,
    updated_at timestamptz,
    updated_by integer,
    CONSTRAINT ck_erp_goods_receipt_line_kind CHECK (kind IN ('ITEM','MATERIAL')),
    CONSTRAINT ck_erp_goods_receipt_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_erp_goods_receipt_line_price CHECK (unit_price >= 0),
    UNIQUE (receipt_id, kind, line_no)
);
CREATE INDEX IF NOT EXISTS ix_erp_goods_receipt_line_receipt ON erp_goods_receipt_line(receipt_id);

CREATE TABLE IF NOT EXISTS erp_stock_movement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_function varchar(64) NOT NULL,
    source_id bigint NOT NULL,
    source_line_id bigint NOT NULL,
    unit_code varchar(20) NOT NULL,
    warehouse_code varchar(20) NOT NULL,
    product_code varchar(64) NOT NULL,
    document_date date NOT NULL,
    quantity numeric(18,4) NOT NULL,
    value numeric(18,2) NOT NULL,
    posted_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_function, source_line_id)
);
CREATE INDEX IF NOT EXISTS ix_erp_stock_movement_balance ON erp_stock_movement(unit_code, warehouse_code, product_code);
CREATE INDEX IF NOT EXISTS ix_erp_stock_movement_source ON erp_stock_movement(source_function, source_id);
