import React from 'react';
import {
  BarChart,
  Layers,
  ShoppingBag,
  DollarSign,
  Users,
  FileSpreadsheet,
  Bot,
  Settings,
  FolderTree,
  Building2,
  Package,
  Warehouse,
  Tag,
  Scale,
  ArrowRightLeft,
  ShieldAlert,
  Boxes,
  MapPin,
  FileText,
  ArrowDownLeft,
  ArrowUpRight,
  PieChart,
  UserCheck,
  CreditCard,
  Calculator,
  Calendar,
  Languages,
  Percent,
  History,
  CheckCircle2,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Coins,
  Download,
  Landmark,
  Network,
  RefreshCw,
  ShieldCheck,
  Sliders,
  TrendingUp,
  Upload,
  Tags,
  PanelLeft,
  LucideProps
} from 'lucide-react';

interface DynamicIconProps extends LucideProps {
  name: string;
}

const iconMap: Record<string, React.FC<LucideProps>> = {
  BarChart,
  Layers,
  ShoppingBag,
  DollarSign,
  Users,
  FileSpreadsheet,
  Bot,
  Settings,
  FolderTree,
  Building2,
  Package,
  Warehouse,
  Tag,
  Scale,
  ArrowRightLeft,
  ShieldAlert,
  Boxes,
  MapPin,
  FileText,
  ArrowDownLeft,
  ArrowUpRight,
  PieChart,
  UserCheck,
  CreditCard,
  Calculator,
  Calendar,
  Languages,
  Percent,
  History,
  CheckCircle2,
  CheckSquare,
  ClipboardCheck,
  Clock,
  Coins,
  Download,
  Landmark,
  Network,
  RefreshCw,
  ShieldCheck,
  Sliders,
  TrendingUp,
  Upload,
  Tags,
  PanelLeft
};

/** Icon names a menu item may use (the structure editor offers these). */
export const ICON_NAMES = Object.keys(iconMap).sort();

export const DynamicIcon: React.FC<DynamicIconProps> = ({ name, ...props }) => {
  const IconComponent = iconMap[name] || FileText;
  return <IconComponent {...props} />;
};
